services:
  app:
    image: ruby:3.4.7
    container_name: unicode-server
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: unicode-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
